import type { Metadata } from 'next';
import { Indie_Flower } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';
import './globals.css';

const indieFlower = Indie_Flower({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={indieFlower.className}>
                {children}
                <Analytics />
            </body>
        </html>
    );
}
